import { Header } from "../../components/Header";
import { NavigationSection } from "../sections/NavigationSection";

export const PrivacyPolicyPage = (): JSX.Element => {
  return (
    <div className="bg-[#f7fbfe] flex flex-col items-center w-full min-h-screen">
      <Header />

      <div className="container max-w-4xl mx-auto px-4 py-12">
        <h1 className="font-bold text-[#1e1e1e] text-[42px] mt-12 [font-family:'Baloo_2',Helvetica] text-center">
          Privacy Policy for Cheeko - Parental App
        </h1>

        <div className="prose prose-lg max-w-none">
          <p className="text-[#1e1e1eb2] mb-6 text-center">
            Last updated: {new Date().toLocaleDateString()}
          </p>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            1. Introduction
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            Welcome to the Privacy Policy for Cheeko - Parental App, developed
            by Altio AI Pvt. Ltd. This policy outlines how we collect, use,
            disclose, and protect your information when you use our application
            to interact with our AI Toy for Kids, which offers features like
            storytelling, puzzle-solving, and math tutoring, along with parental
            controls for toy activation, Wi-Fi setup, and customization.
          </p>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            2. Definitions
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            For the purposes of this Privacy Policy:
          </p>
          <ul className="list-disc pl-6 mb-6 text-[#1e1e1eb2]">
            <li>
              <strong>Account:</strong> A unique account created for You to
              access our Service or parts of our Service.
            </li>
            <li>
              <strong>Affiliate:</strong> An entity that controls, is controlled
              by, or is under common control with a party.
            </li>
            <li>
              <strong>Application:</strong> Refers to Cheeko - Parental App, the
              software program provided by the Company.
            </li>
            <li>
              <strong>Company:</strong> Refers to Altio AI Pvt. Ltd.
            </li>
            <li>
              <strong>Country:</strong> Refers to Karnataka, India.
            </li>
            <li>
              <strong>Device:</strong> Any device that can access the Service,
              such as a computer, cellphone, or digital tablet.
            </li>
            <li>
              <strong>Personal Data:</strong> Information that relates to an
              identified or identifiable individual.
            </li>
            <li>
              <strong>Service:</strong> Refers to the Application.
            </li>
            <li>
              <strong>Service Provider:</strong> Any natural or legal person who
              processes data on behalf of the Company.
            </li>
            <li>
              <strong>Usage Data:</strong> Data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself.
            </li>
            <li>
              <strong>You:</strong> The individual accessing or using the
              Service, or the company or other legal entity on behalf of which
              such individual is accessing or using the Service.
            </li>
          </ul>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            3. Information We Collect
          </h2>
          <h3 className="font-bold text-[#1e1e1e] text-[22px] mt-6 mb-3">
            3.1 Personal Data
          </h3>
          <p className="text-[#1e1e1eb2] mb-4">
            While using our Service, we may collect the following Personal Data
            to provide and tailor experiences:
          </p>
          <ul className="list-disc pl-6 mb-6 text-[#1e1e1eb2]">
            <li>Parent’s name</li>
            <li>Email address</li>
            <li>Kid’s details: name, age, gender, birthday</li>
          </ul>

          <h3 className="font-bold text-[#1e1e1e] text-[22px] mt-6 mb-3">
            3.2 Usage Data
          </h3>
          <p className="text-[#1e1e1eb2] mb-4">
            Usage Data is collected automatically when using the Service and may
            include:
          </p>
          <ul className="list-disc pl-6 mb-6 text-[#1e1e1eb2]">
            <li>IP address</li>
            <li>Browser type and version</li>
            <li>Pages visited within the app</li>
            <li>Time and date of your visit</li>
            <li>Diagnostic data</li>
            <li>
              Mobile device type, unique ID, IP, operating system, and browser
              type (when accessing via mobile)
            </li>
          </ul>

          <h3 className="font-bold text-[#1e1e1e] text-[22px] mt-6 mb-3">
            3.3 Data for Toy Functionality
          </h3>
          <p className="text-[#1e1e1eb2] mb-4">
            To enable toy activation and customization, we collect:
          </p>
          <ul className="list-disc pl-6 mb-6 text-[#1e1e1eb2]">
            <li>Toy serial number and activation key</li>
            <li>Wi-Fi SSID and password</li>
            <li>
              Customization settings: toy name, personality (e.g., storyteller,
              puzzle solver, math tutor), language, voice (e.g., male, female,
              robotic), conversation sensitivity (low, medium, high)
            </li>
          </ul>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            4. How We Use Your Information
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            We use the collected data for the following purposes:
          </p>
          <ul className="list-disc pl-6 mb-6 text-[#1e1e1eb2]">
            <li>
              To provide and maintain our Service, including toy activation and
              Wi-Fi connectivity
            </li>
            <li>To manage Your Account and registration</li>
            <li>
              To customize the toy experience based on provided settings and
              kid’s details
            </li>
            <li>
              To contact You regarding account updates, toy functionality, or
              support
            </li>
            <li>
              To provide news, special offers, and general information about our
              products
            </li>
            <li>To manage Your requests and inquiries</li>
            <li>For business transfers, such as mergers or acquisitions</li>
            <li>
              To analyze and improve our Service, app, and toy functionality
            </li>
          </ul>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            5. Retention of Your Data
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            We will retain Your Personal Data only for as long as necessary for
            the purposes set out in this Privacy Policy. We will retain and use
            Your Personal Data to the extent necessary to comply with our legal
            obligations, resolve disputes, and enforce our legal agreements and
            policies.
          </p>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            6. Transfer of Your Data
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            Your information, including Personal Data, may be transferred to—and
            maintained on—computers located outside of your state, province,
            country, or other governmental jurisdiction where the data
            protection laws may differ from those in your jurisdiction. Your
            consent to this Privacy Policy followed by your submission of such
            information represents your agreement to that transfer.
          </p>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            7. Disclosure of Your Data
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            We may disclose Your Personal Data in the following circumstances:
          </p>
          <ul className="list-disc pl-6 mb-6 text-[#1e1e1eb2]">
            <li>
              <strong>Business Transactions:</strong> If the Company is involved
              in a merger, acquisition, or asset sale, Your Personal Data may be
              transferred.
            </li>
            <li>
              <strong>Legal Obligations:</strong> To comply with a legal
              obligation or in response to a valid request from public
              authorities.
            </li>
            <li>
              <strong>Protection:</strong> To protect and defend the Company’s
              rights or property, prevent or investigate possible wrongdoing, or
              protect the safety of users or the public.
            </li>
            <li>
              <strong>Service Providers:</strong> To share with third-party
              Service Providers who assist in operating our Service, subject to
              confidentiality agreements.
            </li>
          </ul>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            8. Security of Your Data
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            The security of Your Personal Data is important to us. We strive to
            use commercially acceptable means to protect it, but no method of
            transmission over the Internet or electronic storage is 100% secure,
            and we cannot guarantee absolute security.
          </p>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            9. Children's Privacy
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            Our Service is designed for parental use and collects kid’s details
            (name, age, gender, birthday) to tailor the AI Toy experience. We do
            not knowingly collect Personal Data directly from children under 13.
            Parents are responsible for providing and managing their child’s
            data. If we learn we have collected Personal Data from a child under
            13 without parental consent, we will take steps to delete it.
          </p>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            10. Your Data Protection Rights
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            Depending on your location, you may have the following rights
            regarding Your Personal Data:
          </p>
          <ul className="list-disc pl-6 mb-6 text-[#1e1e1eb2]">
            <li>
              <strong>Access:</strong> Request access to Your Personal Data.
            </li>
            <li>
              <strong>Correction:</strong> Request correction of inaccurate or
              incomplete data.
            </li>
            <li>
              <strong>Deletion:</strong> Request deletion of Your Personal Data.
            </li>
            <li>
              <strong>Restriction:</strong> Request restriction of processing
              Your Personal Data.
            </li>
            <li>
              <strong>Objection:</strong> Object to our processing of Your
              Personal Data.
            </li>
            <li>
              <strong>Data Portability:</strong> Request a copy of Your Personal
              Data in a structured, commonly used, and machine-readable format.
            </li>
          </ul>
          <p className="text-[#1e1e1eb2] mb-4">
            To exercise these rights, please contact us using the details below.
          </p>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            11. Changes to This Privacy Policy
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            We may update this Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page
            and updating the "Last updated" date. You are advised to review this
            Privacy Policy periodically for any changes.
          </p>

          <h2 className="font-bold text-[#1e1e1e] text-[28px] mt-8 mb-4">
            12. Contact Us
          </h2>
          <p className="text-[#1e1e1eb2] mb-4">
            If you have any questions about this Privacy Policy, You can contact
            us:
          </p>
          <ul className="list-disc pl-6 mb-6 text-[#1e1e1eb2]">
            <li>
              <strong>Email:</strong> hr@altio.me
            </li>
            <li>
              <strong>Phone:</strong> +91 8310896240
            </li>
            <li>
              <strong>Address:</strong> Altio AI Pvt. Ltd., Survey No. 7/2, 1st
              Floor, Divitigeramanahally, Deepanjalinagar, Bangalore, Karnataka,
              India, 560026
            </li>
          </ul>
        </div>
      </div>

      <NavigationSection />
    </div>
  );
};
